baseURL = ""
languageCode = "fr-fr"
title = "Digital Fun√©raire"
theme = "perso"


[menu]

  [[menu.main]]
    identifier = "home"
    title = "home"
    name = ""
    pre = "<i class='fas fa-home'></i>"
    url = "/index.html/"
    weight = 1

  [[menu.main]]
    identifier = "a propos"
    name = "a propos"
    url = "#"
    weight = 4

      [[menu.main]]
    identifier = "Produits"
    name = "Produits"
    url = "#"
    weight = 2

      [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 3