baseURL = ""
languageCode = "fr-fr"
DefaultContentLanguage = "fr"
lang = "fr"
title = "Tintinou"
theme = "perso"
summaryLength = "10"


[menu]

  [[menu.main]]
    identifier = "home"
    title = "home"
    name = ""
    pre = "<i class='fas fa-home'></i>"
    url = "/index.html/"
    weight = 1

      [[menu.main]]
    identifier = "infos"
    name = "infos"
    url = "infos.html/"
    weight = 4

      [[menu.main]]
    identifier = "Produits"
    name = "Produits"
    url = "/index.html/"
    weight = 2

      [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 3